### ISSUE TITLE
Scheduled cleanup of temp files

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#117]
**ACCEPTANCE CRITERIA**
- [x] A cron job runs nightly that deletes temp files 
- [x] A cron job runs nightly that deletes saved searches from the blacklight database

We do both these things for Laevigata and we should do them in tenejo too.

**Comment by val99erie** [comment]
Something to consider about file cleanup:  Make sure we don't accidentally delete our CSV manifests for CSV imports.

In Hyrax, attached files are uploaded as `Hyrax::UploadedFile` records, and the files are stored in the `Hyrax.config.upload_path`.  These are considered temporary files because when all the background jobs have finished ingesting those files into fedora, we no longer need them.  Normally those background jobs would finish in just a few minutes, so I think most of our production environments just clean up all files older than N days.

But, now we are storing a different type of file.  The CSV manifests aren't temporary files.  They are the permanent storage location for CSV files that are attached to a `CsvImport` record.  We want to keep those files for as long as the corresponding `CsvImport` records exist.

So, there are a couple ways you could handle it...

1. When you clean up the Hyrax uploads dir, make sure you exclude the sub-directory where the CSV files are stored.  That sub-directory is set by default here:
https://github.com/curationexperts/tenejo/blob/master/app/uploaders/csv_manifest_uploader.rb#L48

or:

2. Set an environment variable `CSV_MANIFESTS_PATH` to store the CSV files somewhere outside of the Hyrax uploads dir.
