### ISSUE TITLE
Unable to upload fully filled out CSV

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts-deprecated/tenejo-v1#136]

**Comment by RachelDCE** [comment]
Uploaded csv file. Detected three records. Got errors in the background job.
![Screen Shot 2019-02-04 at 4.03.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5835b9b16342041300e166e0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f76b7191a37cf112284f5e585ecc3c4a4356bcbbd671f3e57862804e0ebfd0645b7dc03c11a5ee854db801ba21d84fd7b0eed84ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df242e24c5da2173363ef772431.png)

Download this file as a csv:

https://docs.google.com/spreadsheets/d/13Kh7Q9qODuNYqubIudeJqtfQxoxaIm8gB_PxvaYJdwQ/edit?usp=sharing

**Comment by bess** [comment]
I believe the problem here is that these files don't exist on the server. I can re-create this error locally if I try to run this spreadsheet with files that don't exist, and I do not get an error if I run this spreadsheet with files that *do* exist.

The error message in sidekiq is really not helpful, so I put in a PR to Darlingtonia (https://github.com/curationexperts/darlingtonia/pull/56) that will provide a more meaningful error message. This should mean that if someone forgets to upload a file, they'll see an error about it being missing, and then if they go upload it the import will work when sidekiq tries again.

**Comment by RachelDCE** [comment]
I downloaded Filezilla and successfully uploaded my files to the server.
