### ISSUE TITLE
Invalid license statement causes application error

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#172]
On `tenejo-cd` right now, you can't view search results because an error is thrown:

[tenejo-cd/production] ActionView::Template::Error: key not found: "term"

From the stack trace, this seems to stem from an invalid license statement value in one of the records, that then cannot be fetched at display time.

## Backtrace

    line 2 of [PROJECT_ROOT]/app/views/hyrax/works/_work.html.erb: _app_views_hyrax_works__work_html_erb___1649879165290214127_70156793074320

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/59580/faults/45502635)

- [x] An invalid license value should cause an error and not be imported

**Comment by mark-dce** [comment]
**CONCERN 1**
I can still create the problem behavior by putting the value "license" as the value for the license in each row of my file.

Instead of checking if the field value is "license" in https://github.com/curationexperts/tenejo/blob/master/app/uploaders/csv_manifest_validator.rb#L97 could you just check if the index is 0?
```
      next if i == 0 # Skip the header row
```

**Concern 2**
Can we read the licenses from the license authority instead of having to maintain a second copy?  This is a place where duplication seems pretty fragile.

Instead of https://github.com/curationexperts/tenejo/blob/master/app/uploaders/csv_manifest_validator.rb#L55-L73, how about something like

```
  def valid_licenses
     @active_ids = @active_ids || Hyrax::LicenseService.new.authority.all.select{ |license| license[:active] }.map{ |license| license[:id] }
  end
```

**Comment by bess** [comment]
refactor submitted here: https://github.com/curationexperts/darlingtonia/pull/63

**Comment by mark-dce** [comment]
![172 - invalid license errors](https://user-images.githubusercontent.com/3064318/52663677-c3852600-2ecc-11e9-9b93-de1578f8256d.png)
