### ISSUE TITLE
Add a read-only-mode to the repository

### ISSUE THREAD

**Issue by bess** [curationexperts-deprecated/tenejo-v1#64]

**Comment by mark-dce** [comment]
**STORY**
As a repository service manager, I would like the ability to place the repository in a read-only mode, so that users can continue to use the repository for discovery but not add new content while I'm doing system upgrades.

**ACCEPTANCE**
- [x] We have a mechanism to put the repository in a `read-only` mode where the repository state can't be changed (no new content, jobs, etc.)
- [x] The homepage indicates when the system has been put in read-only mode
- [x] The dashboard indicates when the system has been put in read-only mode

NOTE:  See the Emory laevigata project for a potential solution.

**Comment by mark-dce** [comment]
Looks good

<img width="1168" alt="64 - read only mode" src="https://user-images.githubusercontent.com/3064318/52618434-72d9e280-2e64-11e9-9ce8-e4f0f7b7e1cc.png">
